name: socially
description: "Havebreak Flutter Task"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.0-1.0.dev

dependencies:
  flutter:
    sdk: flutter
  sprintf: ^7.0.0
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.3.1
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^5.0.1
  get_it: ^7.6.4
  go_router: ^12.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.3.2
  isar: ^3.1.0+1
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  firebase_crashlytics: ^3.4.4
  firebase_core: ^2.22.0
  socially_ui_components:
    path: ../packages/ui_components
  isar_flutter_libs: ^3.1.0+1
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  get: ^4.6.6
  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  socially_analysis:
    path: ../packages/analysis/
  build_runner: ^2.4.6
  dcm: ^1.0.0
  flutter_native_splash: ^2.3.5
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1
  isar_generator: ^3.1.0+1
  flutter_lints: ^5.0.0
  analyzer: ^5.13.0
  freezed: ^2.5.2

flutter_native_splash:
  color: "#05101C"  # Background color of the splash screen
  image: ../packages/ui_components/assets/pngs/logo.png  # Path to your logo or image

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - .env

  